version: '3.7'

services:  
  redis_image:
    image: redis
    ports:
      - "6379:6379"
  db_image:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "q1w2e3!*"
        ACCEPT_EULA: "Y"